# Generated by Django 4.2 on 2023-04-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donator',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('did', models.CharField(db_column='did', max_length=11)),
                ('fname', models.TextField(db_column='fname')),
                ('lname', models.TextField(db_column='lname')),
                ('bloodtype', models.TextField(db_column='bloodtype')),
                ('donation_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
