# Generated by Django 4.2 on 2023-04-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BECS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.IntegerField(db_column='op')),
                ('ap', models.IntegerField(db_column='ap')),
                ('bp', models.IntegerField(db_column='bp')),
                ('abp', models.IntegerField(db_column='abp')),
                ('om', models.IntegerField(db_column='om')),
                ('am', models.IntegerField(db_column='am')),
                ('bm', models.IntegerField(db_column='bm')),
                ('abm', models.IntegerField(db_column='abm')),
            ],
        ),
    ]
