# Generated by Django 4.2 on 2023-04-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BECS', '0002_bloodstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodstock',
            name='id',
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='bid',
            field=models.IntegerField(db_column='bid', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='abm',
            field=models.IntegerField(db_column='abm', default=0),
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='abp',
            field=models.IntegerField(db_column='abp', default=0),
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='am',
            field=models.IntegerField(db_column='am', default=0),
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='ap',
            field=models.IntegerField(db_column='ap', default=0),
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='bm',
            field=models.IntegerField(db_column='bm', default=0),
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='bp',
            field=models.IntegerField(db_column='bp', default=0),
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='om',
            field=models.IntegerField(db_column='om', default=0),
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='op',
            field=models.IntegerField(db_column='op', default=0),
        ),
    ]
