# Generated by Django 4.2 on 2023-05-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BECS', '0003_remove_bloodstock_id_bloodstock_bid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('aid', models.IntegerField(db_column='aid', primary_key=True, serialize=False)),
                ('type', models.TextField(db_column='type')),
                ('btype', models.TextField(db_column='btype')),
                ('qtts', models.IntegerField(db_column='qtts')),
                ('dt', models.TextField(db_column='dt')),
            ],
        ),
    ]
